const fs = require("node:fs/promises");
const path = require("node:path");
const { minify } = require("terser");

const repoRoot = path.resolve(__dirname, "..");
const sourceRoot = path.join(repoRoot, "Sources");
const sourceJsRoot = path.join(sourceRoot, "js");
const distRoot = path.join(repoRoot, "Dist");
const distJsRoot = path.join(distRoot, "js");

const sourceIndexPath = path.join(sourceRoot, "index.html");
const distIndexPath = path.join(distRoot, "index.html");
const distMainBundlePath = path.join(distJsRoot, "main.min.js");
const distWorkerBundlePath = path.join(distJsRoot, "worker-bootstrap.js");

async function build() {
    await fs.rm(distRoot, { force: true, recursive: true });
    await fs.mkdir(distJsRoot, { recursive: true });

    const sourceIndexHtml = await readUtf8(sourceIndexPath);
    const mainScriptPaths = extractClassicScriptPaths(sourceIndexHtml).map((scriptPath) => path.join(sourceRoot, scriptPath));

    const mainBundleSource = await concatenateFiles(mainScriptPaths);
    const minifiedMainBundle = await minifyJavaScript(mainBundleSource, "main.min.js");
    await fs.writeFile(distMainBundlePath, minifiedMainBundle, "utf8");

    const minifiedWorkerBundle = await buildWorkerBundle();
    await fs.writeFile(distWorkerBundlePath, minifiedWorkerBundle, "utf8");

    const distIndexHtml = createDistIndexHtml(sourceIndexHtml);
    await fs.writeFile(distIndexPath, distIndexHtml, "utf8");

    await copyStaticAsset("style.css");
    await copyStaticAsset("favicon.svg");

    console.log(`Generated ${path.relative(repoRoot, distIndexPath)}`);
    console.log(`Generated ${path.relative(repoRoot, distMainBundlePath)}`);
    console.log(`Generated ${path.relative(repoRoot, distWorkerBundlePath)}`);
}

async function buildWorkerBundle() {
    const workerBootstrapPath = path.join(sourceJsRoot, "worker-bootstrap.js");
    const workerBootstrapSource = await readUtf8(workerBootstrapPath);
    const workerDependencyPaths = extractImportScriptsPaths(workerBootstrapSource).map((scriptPath) => path.join(sourceJsRoot, scriptPath));
    const inlinedWorkerBootstrapSource = workerBootstrapSource.replace(/^importScripts\([^\n]*\);\r?\n?/m, "");

    const workerBundleSource = await concatenateFiles([
        ...workerDependencyPaths,
        { label: "js/worker-bootstrap.js", content: inlinedWorkerBootstrapSource },
    ]);

    return minifyJavaScript(workerBundleSource, "worker-bootstrap.js");
}

function createDistIndexHtml(sourceIndexHtml) {
    return sourceIndexHtml.replace(
        /\s*<!-- Classic scripts are loaded in dependency order because modules are not used here\. -->(?:\r?\n\s*<script src="js\/[^"]+" defer><\/script>)+/,
        "\n    <!-- Bundled application script generated by npm run build:min. -->\n    <script src=\"js/main.min.js\" defer></script>",
    );
}

async function concatenateFiles(entries) {
    const chunks = [];

    for (const entry of entries) {
        if (typeof entry === "string") {
            const content = await readUtf8(entry);
            const relativePath = path.relative(sourceRoot, entry).replaceAll("\\", "/");
            chunks.push(`/* ${relativePath} */\n${content.trim()}\n`);
            continue;
        }

        chunks.push(`/* ${entry.label} */\n${entry.content.trim()}\n`);
    }

    return chunks.join("\n;\n\n");
}

function extractClassicScriptPaths(sourceIndexHtml) {
    const scriptMatches = [...sourceIndexHtml.matchAll(/<script src="([^"]+)" defer><\/script>/g)];

    if (scriptMatches.length === 0) {
        throw new Error("No classic script tags were found in Sources/index.html.");
    }

    return scriptMatches.map((match) => match[1]);
}

function extractImportScriptsPaths(workerBootstrapSource) {
    const importScriptsMatch = workerBootstrapSource.match(/importScripts\(([^)]+)\);/);

    if (!importScriptsMatch) {
        throw new Error("worker-bootstrap.js does not contain an importScripts call.");
    }

    return [...importScriptsMatch[1].matchAll(/"([^"]+)"/g)].map((match) => match[1]);
}

async function minifyJavaScript(source, filename) {
    const result = await minify(source, {
        compress: true,
        ecma: 2020,
        format: { comments: false },
        mangle: true,
        module: false,
    });

    if (!result.code) {
        throw new Error(`Terser did not emit output for ${filename}.`);
    }

    return result.code;
}

async function copyStaticAsset(relativePath) {
    await fs.copyFile(path.join(sourceRoot, relativePath), path.join(distRoot, relativePath));
}

async function readUtf8(filePath) {
    return fs.readFile(filePath, "utf8");
}

build().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});